import{lyric,scenes,completeUnit,canDeliver,contrastEligible,acceptLine}from'./demo-core.mjs';
const $=id=>document.getElementById(id);let epoch=0,scene='work',saved=null;const delivered=new Set();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function element(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;}
function scroll(){const n=$('messages');n.scrollTop=n.scrollHeight;}
function message(role,text){const row=element('div','message '+role);if(role!=='user')row.append(element('span','name','小乐'));row.append(element('div','bubble',text));$('messages').append(row);scroll();}
function status(text){const n=element('div','status',text);$('messages').append(n);scroll();return n;}
function choices(items){$('choices').replaceChildren(...items.map(([label,action])=>{const b=element('button','',label);b.type='button';b.onclick=action;return b;}));}
async function replies(user,lines,next){const stamp=epoch;choices([]);if(user)message('user',user);for(const line of lines){await wait(420);if(stamp!==epoch)return;message('assistant',line);}if(stamp===epoch&&next)next();}
function card(title,text,kind){const n=element('div','media-card');n.append(element('strong','',title),element('p','',text));if(kind==='sing'){const wave=element('div','wave');wave.setAttribute('aria-hidden','true');for(let i=0;i<32;i++)wave.append(element('i'));n.append(wave,element('small','','跟唱卡片示意 · 不含音频，不代表模型生成'));}else{const line=element('div','timeline');line.append(element('span','','安静练习'),element('span','','动作展开'));n.append(line,element('div','music-strip'),element('small','','同一连续音乐片段 · 转折同步 · 预置示意，无视频导出'));}$('messages').append(n);scroll();}
async function sing(){const unit=completeUnit('把晚风装进口袋',[{text:lyric,aligned:true}]);const job={epoch,work:'fictional-work',key:'sing:'+epoch};const hint=status('小乐在准备这一句…（模拟等待）');choices([['切换话题，看看迟到结果怎么处理',()=>select('writing')]]);await wait(1000);if(!canDeliver(job,{epoch,work:'fictional-work'},delivered))return;hint.remove();delivered.add(job.key);card('♪ 这一句，唱给你听',unit.text,'sing');choices([['聊聊这句为什么打动你',()=>replies('这句哪里打动你呀？',['像是舍不得把今天用完，还想给明天藏一点好心情。'],()=>choices([['一起写一句新的',()=>select('writing')]]))]]);}
function notebook(){ $('saved-count').textContent=saved?'1':'0';$('saved-line').textContent=saved||'认可之后，这一句才留下来。';}
function work(){const n=element('div','work-card','♫ 口袋里的晚风');n.append(element('small','','虚构示例作品 · 无真实音频上传'));$('messages').append(n);choices([['听听我新写的歌怎么样？',()=>replies('听听我新写的歌怎么样？',['像一天忙完，终于走上回家的路。不是一下子开心起来，是慢慢松了一口气。','我喜欢“把晚风装进口袋，留一半给明天”。好像明天也没那么可怕了。'],sing)]]);}
function writing(){message('assistant','今天想写一点什么？');choices([['写下班路上的疲惫，但又有点期待',()=>replies('写下班路上的疲惫，但又有点期待',['可以把那一点期待藏得轻一点——“末班车收走疲惫，车窗替我留着光。”'],()=>choices([['这句我喜欢，记下来吧',()=>{saved=acceptLine('末班车收走疲惫，车窗替我留着光。',true);notebook();replies('这句我喜欢，记下来吧',['记下来了。那一点光，留给你慢慢往下写。'],()=>{const n=element('div','saved-marker','已记入本次演示的歌词本');$('messages').append(n);choices([['看看 Mlog 怎么邀约',()=>select('mlog')]]);});}],['还不是这个感觉',()=>replies('还不是这个感觉',['那让它再轻一点：“今天的风不赶路，我也慢慢走。”'],()=>choices([['就记这一句',()=>{saved=acceptLine('今天的风不赶路，我也慢慢走。',true);notebook();replies('就记这一句',['好，替你留住了。']);}]]))]]))]]);}
function mlog(){const n=element('div','work-card','▧ 两段日常素材');n.append(element('small','','安静练习 / 热烈排练 · 虚构素材，不读取文件'));$('messages').append(n);choices([['这些都是最近随手拍的',()=>replies('这些都是最近随手拍的',['前一段像在和自己相处，后一段整个人都亮起来了。','你那首歌也有从收着到放开的地方。要不要把这两种状态接成一小段音乐日记？'],()=>choices([['好呀，试试看',async()=>{const stamp=epoch;message('user','好呀，试试看');choices([]);const n=status('小乐在准备这段音乐日记…（模拟等待）');await wait(950);if(stamp!==epoch)return;n.remove();if(contrastEligible({videoContrast:true,musicContrast:true,continuousMusic:true,syncOffsetMs:0}))card('状态反差 · 音乐日记构思','画面从练习切到排练，音乐在同一处展开。','mlog');choices([['这次先不剪了',()=>replies('这次先不剪了',['好呀，留着这两个状态也很有意思。'])]]);}],['先不剪，就聊聊',()=>replies('先不剪，就聊聊',['排练里那个突然放开的瞬间，看着就很痛快。那天练得顺吗？'])]]))]]);}
function select(key){epoch++;scene=key;delivered.clear();$('messages').replaceChildren();choices([]);const s=scenes[key];$('note-title').textContent=s.title;$('note-copy').textContent=s.copy;$('rule-title').textContent=s.rule;$('rule-copy').textContent=s.detail;document.querySelectorAll('[data-scene]').forEach(b=>{b.classList.toggle('active',b.dataset.scene===key);b.setAttribute('aria-pressed',String(b.dataset.scene===key));});({work,writing,mlog})[key]();}
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>select(b.dataset.scene));$('reset').onclick=()=>{saved=null;notebook();select(scene);};select('work');
